name: lipslay_flutter_frontend
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  country_picker: ^2.0.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  carousel_slider: ^4.1.1 
  font_awesome_flutter: ^10.7.0 
  url_launcher: ^6.2.2
  table_calendar: ^3.0.9 


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:



  uses-material-design: true


  assets:
    - assets/images/
    - assets/data/countries.json 

  # fonts:
  #   - family: Ubuntu 
  #     fonts:
  #       - asset: assets/fonts/Ubuntu-Regular.ttf
  #       - asset: assets/fonts/Ubuntu-Bold.ttf
  #         weight: 700
  